# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestLoginregisrtarationtest():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_registration(self):
    self.driver.get("https://deliveraddis.com/")
    self.driver.set_window_size(1382, 784)
    self.driver.find_element(By.CSS_SELECTOR, ".login-trigger > .dropdown").click()
    self.driver.find_element(By.CSS_SELECTOR, ".orange").click()
    self.driver.find_element(By.NAME, "firstname").send_keys("Jemila")
    self.driver.find_element(By.NAME, "lastname").click()
    self.driver.find_element(By.NAME, "lastname").send_keys("Bekele")
    self.driver.find_element(By.NAME, "telephone").send_keys("715-343-976")
    self.driver.find_element(By.CSS_SELECTOR, ".two:nth-child(2) > .required > input").click()
    self.driver.find_element(By.CSS_SELECTOR, ".two:nth-child(2) > .required > input").send_keys("bekelehussen48@gmail.com")
    self.driver.find_element(By.NAME, "password1").click()
    self.driver.find_element(By.NAME, "password1").send_keys("!QAZxsw2")
    self.driver.find_element(By.NAME, "password2").click()
    self.driver.find_element(By.NAME, "password2").send_keys("!QAZxsw2")
    self.driver.find_element(By.NAME, "location_name").click()
    self.driver.find_element(By.NAME, "location_description").click()
    self.driver.find_element(By.CSS_SELECTOR, ".mapboxgl-canvas").click()
    self.driver.find_element(By.CSS_SELECTOR, "g:nth-child(3) > path").click()
    self.driver.find_element(By.NAME, "location_description").click()
    self.driver.find_element(By.NAME, "location_description").send_keys("balcha hospital")
    self.driver.find_element(By.CSS_SELECTOR, ".green").click()
    self.driver.find_element(By.NAME, "location_name").click()
    self.driver.find_element(By.CSS_SELECTOR, ".mapboxgl-canvas").click()
    self.driver.find_element(By.CSS_SELECTOR, ".mapboxgl-canvas").click()
    self.driver.find_element(By.NAME, "location_name").click()
    self.driver.find_element(By.NAME, "location_name").send_keys("work")
    self.driver.find_element(By.CSS_SELECTOR, ".green").click()
  
  def test_logintest(self):
    self.driver.get("https://deliveraddis.com/")
    self.driver.set_window_size(1382, 784)
    self.driver.find_element(By.LINK_TEXT, "Log in").click()
    self.driver.find_element(By.LINK_TEXT, "Log in").click()
    self.driver.find_element(By.LINK_TEXT, "Log in").click()
    self.driver.find_element(By.CSS_SELECTOR, ".ui:nth-child(2) > .ui:nth-child(2) > input").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".ui:nth-child(2) > .ui:nth-child(2) > input")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".ui:nth-child(2) > .ui:nth-child(2) > input").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".ui:nth-child(2) > .ui:nth-child(2) > input")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".ui:nth-child(2) > .ui:nth-child(2) > input").click()
    self.driver.find_element(By.CSS_SELECTOR, ".fluid:nth-child(7)").click()
  
